//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace com.drollic.app.dreamer.core.com.drollic.app.dreamer.webservices.offline {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DreamerOfflineServiceBinding", Namespace="http://offlineservices.dreamer.app.drollic.com")]
    public partial class DreamerOfflineService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetOfflineDreamRequestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public DreamerOfflineService() {
            this.Url = global::com.drollic.app.dreamer.core.Properties.Settings.Default.com_drollic_app_dreamer_core_com_drollic_www_dreamer_webservices_offline_DreamerOfflineService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetOfflineDreamRequestCompletedEventHandler GetOfflineDreamRequestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://www.drollic.com/projects/dreamer/webservices/DreamerOfflineServices.php/Ge" +
            "tOfflineDreamRequest", RequestNamespace="http://offlineservices.dreamer.app.drollic.com", ResponseNamespace="http://offlineservices.dreamer.app.drollic.com")]
        [return: System.Xml.Serialization.SoapElementAttribute("Result")]
        public string GetOfflineDreamRequest(string servercounter) {
            object[] results = this.Invoke("GetOfflineDreamRequest", new object[] {
                        servercounter});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOfflineDreamRequestAsync(string servercounter) {
            this.GetOfflineDreamRequestAsync(servercounter, null);
        }
        
        /// <remarks/>
        public void GetOfflineDreamRequestAsync(string servercounter, object userState) {
            if ((this.GetOfflineDreamRequestOperationCompleted == null)) {
                this.GetOfflineDreamRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOfflineDreamRequestOperationCompleted);
            }
            this.InvokeAsync("GetOfflineDreamRequest", new object[] {
                        servercounter}, this.GetOfflineDreamRequestOperationCompleted, userState);
        }
        
        private void OnGetOfflineDreamRequestOperationCompleted(object arg) {
            if ((this.GetOfflineDreamRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOfflineDreamRequestCompleted(this, new GetOfflineDreamRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetOfflineDreamRequestCompletedEventHandler(object sender, GetOfflineDreamRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOfflineDreamRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOfflineDreamRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591